### ISSUE TITLE
[Switch] react-ios-switch is now using inline styles

### ISSUE THREAD

**Issue by mking-clari** [negativetwelve/react-x#31]
Hey negativetwelve, in v0.1.16, I'm using inline styles instead of css. This should make it even easier for others to use react-x!

Let me know if you have any feedback about the change. It's backwards compatible (in the npm package, there is a placeholder css file to avoid breaking existing code).

**Comment by negativetwelve** [comment]
Hi @mking-clari, thanks for opening this issue! Would love to get this change into react-x. I think it's okay to not include the css file anymore as it requires extra setup on the webpack side. We can remove those extra instructions from the README as well.

Would you like to submit a PR for this? If not, I'll gladly make the change tomorrow sometime (traveling today haha). thanks!

**Comment by negativetwelve** [comment]
Went ahead and included the update in #32!

**Comment by negativetwelve** [comment]
thanks again for taking the time to leave this issue! really appreciate the communication about your project :)
